import { useState, useMemo } from 'react'
import { ChevronDown, ChevronUp, Download, CheckCircle } from 'lucide-react'

export default function DynamicForm({ formJson, profile, onSubmit, readOnly = false }) {
  const [formData, setFormData] = useState(() => {
    if (!formJson?.fields) return {}
    const initial = {}
    formJson.fields.forEach(f => {
      if (f.auto_fill && profile && profile[f.auto_fill] !== undefined) {
        initial[f.name] = profile[f.auto_fill]
      } else if (f.type === 'declaration') {
        initial[f.name] = false
      } else if (f.type === 'checkbox') {
        initial[f.name] = []
      } else if (f.default !== undefined) {
        initial[f.name] = f.default
      } else {
        initial[f.name] = ''
      }
    })
    return initial
  })

  const [errors, setErrors] = useState({})
  const [expandedSections, setExpandedSections] = useState({})

  if (!formJson) return null

  const sections = formJson.sections || [{ key: 'default', title: 'Form', fields: formJson.fields || [] }]
  const docs = formJson.documents || []

  const toggleSection = (key) => {
    setExpandedSections(prev => ({ ...prev, [key]: !prev[key] }))
  }

  const setValue = (name, value) => {
    setFormData(prev => ({ ...prev, [name]: value }))
    if (errors[name]) {
      setErrors(prev => ({ ...prev, [name]: '' }))
    }
  }

  const formatAadhaar = (val) => {
    const digits = val.replace(/\D/g, '').slice(0, 12)
    const parts = []
    for (let i = 0; i < digits.length; i += 4) {
      parts.push(digits.slice(i, i + 4))
    }
    return parts.join('-')
  }

  const formatPhone = (val) => {
    const digits = val.replace(/\D/g, '').slice(0, 10)
    if (digits.length <= 5) return digits
    return `+91 ${digits.slice(0, 5)} ${digits.slice(5)}`
  }

  const validate = () => {
    const newErrors = {}
    formJson.fields.forEach(f => {
      if (f.required && !formData[f.name] && formData[f.name] !== 0) {
        newErrors[f.name] = 'This field is required'
      }
      if (f.validation) {
        const val = formData[f.name]
        if (f.validation.min_length && String(val).length < f.validation.min_length) {
          newErrors[f.name] = `Minimum ${f.validation.min_length} characters required`
        }
        if (f.validation.pattern && val) {
          try {
            const re = new RegExp(f.validation.pattern)
            if (!re.test(String(val))) newErrors[f.name] = f.validation.message || 'Invalid format'
          } catch {}
        }
      }
      if (f.type === 'aadhaar' && val) {
        const digits = String(val).replace(/\D/g, '')
        if (digits.length !== 12) newErrors[f.name] = 'Aadhaar must be 12 digits'
      }
      if (f.type === 'phone' && val) {
        const digits = String(val).replace(/\D/g, '')
        if (digits.length !== 10) newErrors[f.name] = 'Phone must be 10 digits'
      }
      if (f.type === 'email' && val) {
        if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(val)) newErrors[f.name] = 'Invalid email address'
      }
      if (f.type === 'declaration' && f.required && !val) {
        newErrors[f.name] = 'You must accept the declaration'
      }
    })
    setErrors(newErrors)
    return Object.keys(newErrors).length === 0
  }

  const handleSubmit = (e) => {
    e.preventDefault()
    if (validate()) {
      onSubmit?.(formData)
    }
  }

  const handleDownloadPDF = () => {
    let content = `${formJson.title || 'Application Form'}\n${'='.repeat(40)}\n\n`
    sections.forEach(section => {
      content += `${section.title}\n${'-'.repeat(20)}\n`
      section.fields.forEach(f => {
        const val = formData[f.name] || '-'
        content += `${f.label || f.name}: ${String(val)}\n`
      })
      content += '\n'
    })
    if (docs.length > 0) {
      content += 'Documents Required:\n'
      docs.forEach(d => { content += `✓ ${typeof d === 'string' ? d : d.label}\n` })
    }
    content += `\n---\nGenerated by Scheme Sarthi`
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `scheme-sarthi-form.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  const renderField = (field) => {
    const val = formData[field.name]
    const error = errors[field.name]
    const inputClass = `w-full h-[52px] px-4 rounded-xl border-2 ${error ? 'border-danger' : 'border-gray-200'} bg-white text-[16px] text-text-primary focus:outline-none focus:ring-2 focus:ring-primary/30 focus:border-primary font-sans`

    switch (field.type) {
      case 'aadhaar':
        return (
          <div>
            <input
              type="text"
              value={val}
              onChange={e => setValue(field.name, formatAadhaar(e.target.value))}
              placeholder="XXXX-XXXX-XXXX"
              maxLength={14}
              className={`${inputClass} tracking-widest font-mono text-center`}
              readOnly={readOnly}
              disabled={readOnly}
            />
            {error && <p className="text-[12px] text-danger mt-1">{error}</p>}
          </div>
        )

      case 'phone':
        return (
          <div>
            <input
              type="text"
              value={val}
              onChange={e => setValue(field.name, formatPhone(e.target.value))}
              placeholder="+91 XXXXX XXXXX"
              className={inputClass}
              readOnly={readOnly}
              disabled={readOnly}
            />
            {error && <p className="text-[12px] text-danger mt-1">{error}</p>}
          </div>
        )

      case 'email':
        return (
          <div>
            <input
              type="email"
              value={val}
              onChange={e => setValue(field.name, e.target.value)}
              placeholder={field.placeholder || 'email@example.com'}
              className={inputClass}
              readOnly={readOnly}
              disabled={readOnly}
            />
            {error && <p className="text-[12px] text-danger mt-1">{error}</p>}
          </div>
        )

      case 'number':
        return (
          <div>
            <input
              type="number"
              value={val}
              onChange={e => setValue(field.name, e.target.value)}
              placeholder={field.placeholder || ''}
              min={field.min}
              max={field.max}
              className={inputClass}
              readOnly={readOnly}
              disabled={readOnly}
            />
            {error && <p className="text-[12px] text-danger mt-1">{error}</p>}
          </div>
        )

      case 'date':
        return (
          <div>
            <input
              type="date"
              value={val}
              onChange={e => setValue(field.name, e.target.value)}
              className={inputClass}
              readOnly={readOnly}
              disabled={readOnly}
            />
            {error && <p className="text-[12px] text-danger mt-1">{error}</p>}
          </div>
        )

      case 'select':
        return (
          <div>
            <select
              value={val}
              onChange={e => setValue(field.name, e.target.value)}
              className={inputClass}
              disabled={readOnly}
            >
              <option value="">{field.placeholder || 'Select...'}</option>
              {(field.options || []).map(opt => (
                <option key={typeof opt === 'string' ? opt : opt.value} value={typeof opt === 'string' ? opt : opt.value}>
                  {typeof opt === 'string' ? opt : opt.label}
                </option>
              ))}
            </select>
            {error && <p className="text-[12px] text-danger mt-1">{error}</p>}
          </div>
        )

      case 'radio':
        return (
          <div className="space-y-2">
            <div className="flex flex-wrap gap-2">
              {(field.options || []).map(opt => {
                const optVal = typeof opt === 'string' ? opt : opt.value
                const optLabel = typeof opt === 'string' ? opt : opt.label
                const selected = val === optVal
                return (
                  <button
                    key={optVal}
                    type="button"
                    onClick={() => !readOnly && setValue(field.name, optVal)}
                    className={`px-4 py-2.5 rounded-xl text-[14px] font-medium transition-all ${
                      selected ? 'bg-primary text-white shadow-md' : 'bg-primary-light text-primary'
                    }`}
                    disabled={readOnly}
                  >
                    {optLabel}
                  </button>
                )
              })}
            </div>
            {error && <p className="text-[12px] text-danger">{error}</p>}
          </div>
        )

      case 'checkbox':
        return (
          <div className="space-y-1.5">
            {(field.options || []).map(opt => {
              const optVal = typeof opt === 'string' ? opt : opt.value
              const optLabel = typeof opt === 'string' ? opt : opt.label
              const checked = Array.isArray(val) && val.includes(optVal)
              return (
                <label key={optVal} className="flex items-center gap-2.5 py-1.5">
                  <input
                    type="checkbox"
                    checked={checked}
                    onChange={() => {
                      if (readOnly) return
                      const next = checked ? val.filter(x => x !== optVal) : [...(val || []), optVal]
                      setValue(field.name, next)
                    }}
                    className="w-4 h-4 rounded border-gray-300 text-primary focus:ring-primary"
                    disabled={readOnly}
                  />
                  <span className="text-[14px] text-text-primary">{optLabel}</span>
                </label>
              )
            })}
            {error && <p className="text-[12px] text-danger">{error}</p>}
          </div>
        )

      case 'textarea':
        return (
          <div>
            <textarea
              value={val}
              onChange={e => setValue(field.name, e.target.value)}
              placeholder={field.placeholder || ''}
              rows={4}
              className={`w-full px-4 py-3 rounded-xl border-2 ${error ? 'border-danger' : 'border-gray-200'} bg-white text-[16px] text-text-primary focus:outline-none focus:ring-2 focus:ring-primary/30 focus:border-primary font-sans resize-none`}
              readOnly={readOnly}
              disabled={readOnly}
            />
            {error && <p className="text-[12px] text-danger mt-1">{error}</p>}
          </div>
        )

      case 'declaration':
        return (
          <div className={`bg-amber-50 border border-amber-200 rounded-xl p-4 ${error ? 'border-danger' : ''}`}>
            <label className="flex items-start gap-3 cursor-pointer">
              <input
                type="checkbox"
                checked={!!val}
                onChange={e => setValue(field.name, e.target.checked)}
                className="w-4 h-4 rounded border-gray-300 text-primary focus:ring-primary mt-0.5"
                disabled={readOnly}
              />
              <span className="text-[13px] text-text-primary leading-relaxed">{field.label || field.text || 'I confirm the above information is true'}</span>
            </label>
            {error && <p className="text-[12px] text-danger mt-1">{error}</p>}
          </div>
        )

      default:
        return (
          <div>
            <input
              type="text"
              value={val}
              onChange={e => setValue(field.name, e.target.value)}
              placeholder={field.placeholder || ''}
              className={inputClass}
              readOnly={readOnly}
              disabled={readOnly}
            />
            {error && <p className="text-[12px] text-danger mt-1">{error}</p>}
          </div>
        )
    }
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      {sections.map(section => {
        const isExpanded = expandedSections[section.key] !== false

        return (
          <div key={section.key} className="bg-white rounded-2xl shadow-card overflow-hidden">
            <button
              type="button"
              onClick={() => toggleSection(section.key)}
              className="w-full flex items-center justify-between px-4 py-3 border-b border-gray-50 min-h-[48px]"
            >
              <span className="text-[14px] font-semibold text-text-primary">{section.title}</span>
              {isExpanded ? <ChevronUp size={18} className="text-text-secondary" /> : <ChevronDown size={18} className="text-text-secondary" />}
            </button>
            {isExpanded && (
              <div className="px-4 py-3 space-y-4">
                {section.fields.map(f => (
                  <div key={f.name}>
                    {f.type !== 'declaration' && f.label && (
                      <label className="block text-[13px] font-medium text-text-secondary mb-1.5">
                        {f.label}
                        {f.required && <span className="text-danger ml-0.5">*</span>}
                      </label>
                    )}
                    {renderField(f)}
                  </div>
                ))}
              </div>
            )}
          </div>
        )
      })}

      {docs.length > 0 && (
        <div className="bg-white rounded-2xl p-4 shadow-card">
          <h4 className="text-[14px] font-semibold mb-3">Required Documents</h4>
          <div className="space-y-2">
            {docs.map((doc, i) => (
              <div key={i} className="flex items-center gap-2.5 text-[13px]">
                <CheckCircle size={14} className="text-green flex-shrink-0" />
                <span className="text-text-primary">{typeof doc === 'string' ? doc : doc.label}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      <div className="flex gap-3 pt-2">
        {!readOnly && (
          <button type="submit" className="btn-primary flex-1">
            {formJson.submitLabel || 'Submit Application'}
          </button>
        )}
        <button type="button" onClick={handleDownloadPDF} className={`${readOnly ? 'btn-primary' : 'btn-secondary'} flex-shrink-0 px-4`}
          style={{ width: readOnly ? '100%' : 'auto' }}>
          <Download size={18} />
        </button>
      </div>
    </form>
  )
}
