import { useState } from 'react'
import { AlertTriangle, HelpCircle, FileText, FormInput, Download, MapPin, RefreshCw, CheckCircle, Bell, ArrowLeft, ArrowRight, X } from 'lucide-react'

const steps = [
  { key: 'issue', icon: AlertTriangle, label: 'Issue Detected' },
  { key: 'why', icon: HelpCircle, label: 'Why This Happened' },
  { key: 'docs', icon: FileText, label: 'Documents Required' },
  { key: 'form', icon: FormInput, label: 'Auto-filled Application' },
  { key: 'pdf', icon: Download, label: 'Download PDF' },
  { key: 'submit', icon: MapPin, label: 'Where to Submit' },
  { key: 'track', icon: RefreshCw, label: 'Track Application' },
  { key: 'restored', icon: CheckCircle, label: 'Benefit Restored' },
  { key: 'reminders', icon: Bell, label: 'Future Reminders Enabled' },
]

export default function RevivalJourney({ scheme, onClose, profile }) {
  const [currentStep, setCurrentStep] = useState(0)
  const [formData, setFormData] = useState({})
  const [remindersEnabled, setRemindersEnabled] = useState(true)

  const step = steps[currentStep]
  const isFirst = currentStep === 0
  const isLast = currentStep === steps.length - 1
  const progress = ((currentStep + 1) / steps.length) * 100

  const handleNext = () => {
    if (currentStep < steps.length - 1) setCurrentStep(s => s + 1)
  }

  const handleBack = () => {
    if (currentStep > 0) setCurrentStep(s => s - 1)
  }

  const handleDownloadPDF = () => {
    const content = [
      `Scheme: ${scheme?.name_en || scheme?.name_hi || ''}`,
      `Applicant: ${profile?.name || ''}`,
      `Aadhaar: ${profile?.aadhaar || ''}`,
      `---`,
      `This application is auto-generated by Scheme Sarthi`,
      `DPDP Compliant | Your data stays with you`,
    ].join('\n')
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `scheme-sarthi-${scheme?.scheme_id || 'application'}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  const renderStep = () => {
    switch (step.key) {
      case 'issue':
        return (
          <div className="text-center space-y-4">
            <div className="w-16 h-16 mx-auto rounded-full bg-danger/10 flex items-center justify-center">
              <AlertTriangle size={32} className="text-danger" />
            </div>
            <h3 className="text-[18px] font-bold">Issue Detected</h3>
            <p className="text-[14px] text-text-secondary leading-relaxed">
              {scheme?.reason_en || scheme?.reason_hi || 'Your scheme has lapsed or is at risk of lapsing.'}
            </p>
            {scheme?.reasons_en && scheme.reasons_en.length > 0 && (
              <ul className="text-left space-y-2">
                {scheme.reasons_en.map((r, i) => (
                  <li key={i} className="flex items-start gap-2 text-[13px] text-text-secondary">
                    <span className="text-danger mt-0.5">•</span>
                    {r}
                  </li>
                ))}
              </ul>
            )}
            <div className="bg-amber-50 rounded-xl p-3 text-[12px] text-warning">
              Priority: {scheme?.priority || 'Medium'} | Benefit at risk: {scheme?.benefit_amount || 'N/A'}
            </div>
          </div>
        )

      case 'why':
        return (
          <div className="text-center space-y-4">
            <div className="w-16 h-16 mx-auto rounded-full bg-primary-light flex items-center justify-center">
              <HelpCircle size={32} className="text-primary" />
            </div>
            <h3 className="text-[18px] font-bold">Why This Happened</h3>
            <div className="bg-primary-light rounded-2xl p-4 text-left">
              <p className="text-[14px] text-text-primary leading-relaxed">
                {scheme?.reason_en || scheme?.reason_hi || 'The scheme may have lapsed due to missed renewal, incomplete eKYC, or change in eligibility criteria.'}
              </p>
            </div>
            <div className="text-left space-y-2">
              <p className="text-[13px] font-medium text-text-secondary">Common causes:</p>
              <ul className="space-y-1.5">
                {[
                  'Annual eKYC not completed',
                  'Bank account details changed',
                  'Income threshold exceeded',
                  'Residence proof not updated',
                ].map((cause, i) => (
                  <li key={i} className="flex items-center gap-2 text-[13px] text-text-secondary">
                    <span className="w-1.5 h-1.5 rounded-full bg-primary" />
                    {cause}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        )

      case 'docs':
        return (
          <div className="space-y-4">
            <div className="text-center">
              <div className="w-16 h-16 mx-auto rounded-full bg-primary-light flex items-center justify-center">
                <FileText size={32} className="text-primary" />
              </div>
              <h3 className="text-[18px] font-bold mt-3">Documents Required</h3>
            </div>
            <div className="space-y-2">
              {(scheme?.documents || [
                'Aadhaar Card',
                'Bank Account Details',
                'Passport Size Photo',
                'Residence Proof',
              ]).map((doc, i) => (
                <div key={i} className="flex items-center gap-3 bg-white rounded-xl p-3 shadow-card">
                  <div className="w-8 h-8 rounded-full bg-green/10 flex items-center justify-center">
                    <CheckCircle size={16} className="text-green" />
                  </div>
                  <span className="text-[14px] text-text-primary">{doc}</span>
                </div>
              ))}
            </div>
          </div>
        )

      case 'form':
        return (
          <div className="space-y-4">
            <div className="text-center">
              <div className="w-16 h-16 mx-auto rounded-full bg-primary-light flex items-center justify-center">
                <FormInput size={32} className="text-primary" />
              </div>
              <h3 className="text-[18px] font-bold mt-3">Auto-filled Application</h3>
            </div>
            <div className="bg-primary-light/50 rounded-2xl p-4 space-y-3">
              {[
                { label: 'Name', value: profile?.name || '-' },
                { label: 'Age', value: profile?.age || '-' },
                { label: 'Gender', value: profile?.gender || '-' },
                { label: 'State', value: profile?.state || '-' },
                { label: 'District', value: profile?.district || '-' },
                { label: 'Occupation', value: profile?.occupation || '-' },
              ].map((f, i) => (
                <div key={i} className="flex justify-between items-center">
                  <span className="text-[13px] text-text-secondary">{f.label}</span>
                  <span className="text-[13px] font-medium text-text-primary">{f.value}</span>
                </div>
              ))}
            </div>
            <div className="bg-green/5 border border-green/20 rounded-xl p-3 text-center">
              <p className="text-[12px] text-green font-medium">✓ All fields pre-filled from your profile</p>
            </div>
            <div className="space-y-3">
              {[
                { name: 'aadhaar', label: 'Aadhaar Number', value: profile?.aadhaar || '' },
                { name: 'bank_account', label: 'Bank Account Number', value: '' },
                { name: 'ifsc', label: 'IFSC Code', value: '' },
                { name: 'mobile', label: 'Mobile Number', value: profile?.phone || '' },
              ].map(f => (
                <div key={f.name}>
                  <label className="text-[13px] font-medium text-text-secondary block mb-1">{f.label}</label>
                  <input
                    type="text"
                    value={formData[f.name] !== undefined ? formData[f.name] : f.value}
                    onChange={e => setFormData(prev => ({ ...prev, [f.name]: e.target.value }))}
                    className="form-input text-[14px]"
                    placeholder={f.label}
                  />
                </div>
              ))}
            </div>
          </div>
        )

      case 'pdf':
        return (
          <div className="text-center space-y-4">
            <div className="w-16 h-16 mx-auto rounded-full bg-primary-light flex items-center justify-center">
              <Download size={32} className="text-primary" />
            </div>
            <h3 className="text-[18px] font-bold">Download PDF</h3>
            <p className="text-[14px] text-text-secondary">
              Download the auto-filled application form. Print it and submit at the nearest office or CSC.
            </p>
            <button onClick={handleDownloadPDF} className="btn-primary max-w-xs mx-auto">
              <Download size={18} />
              Download Application PDF
            </button>
          </div>
        )

      case 'submit':
        return (
          <div className="space-y-4">
            <div className="text-center">
              <div className="w-16 h-16 mx-auto rounded-full bg-primary-light flex items-center justify-center">
                <MapPin size={32} className="text-primary" />
              </div>
              <h3 className="text-[18px] font-bold mt-3">Where to Submit</h3>
            </div>
            <div className="bg-white rounded-2xl p-4 shadow-card space-y-3">
              <h4 className="text-[13px] font-semibold text-text-secondary uppercase tracking-wide">Official Website</h4>
              {scheme?.apply_url ? (
                <a href={scheme.apply_url} target="_blank" rel="noopener noreferrer"
                  className="flex items-center gap-2 text-[13px] text-primary font-medium hover:underline">
                  {scheme.apply_url}
                </a>
              ) : (
                <p className="text-[13px] text-text-secondary">Visit the official department website</p>
              )}
            </div>
            <div className="bg-amber-50 border border-amber-200 rounded-2xl p-4">
              <div className="flex items-center gap-2 text-[13px] text-warning font-medium mb-1">
                <MapPin size={16} /> Nearest CSC
              </div>
              <p className="text-[12px] text-text-secondary">
                Visit your nearest Common Service Centre (CSC) for assisted submission. Carry all required documents.
              </p>
            </div>
          </div>
        )

      case 'track':
        return (
          <div className="space-y-4">
            <div className="text-center">
              <div className="w-16 h-16 mx-auto rounded-full bg-primary-light flex items-center justify-center">
                <RefreshCw size={32} className="text-primary" />
              </div>
              <h3 className="text-[18px] font-bold mt-3">Track Application</h3>
            </div>
            <div className="space-y-1">
              {[
                { label: 'Application Submitted', done: true },
                { label: 'Document Verification', done: true },
                { label: 'Block Office Review', done: false },
                { label: 'Sanctioned', done: false },
                { label: 'Benefit Restored', done: false },
              ].map((s, i) => (
                <div key={i} className="flex items-center gap-3 py-2">
                  <div className={`w-6 h-6 rounded-full flex items-center justify-center text-[11px] ${
                    s.done ? 'bg-green text-white' : 'bg-gray-200 text-gray-400'
                  }`}>
                    {s.done ? '✓' : String(i + 1)}
                  </div>
                  <span className={`text-[13px] ${s.done ? 'text-green font-medium' : 'text-text-secondary'}`}>
                    {s.label}
                  </span>
                </div>
              ))}
            </div>
            <div className="bg-primary-light rounded-xl p-3 text-center">
              <p className="text-[12px] text-primary">Track your application status in the Applications tab</p>
            </div>
          </div>
        )

      case 'restored':
        return (
          <div className="text-center space-y-4">
            <div className="w-20 h-20 mx-auto rounded-full bg-green/10 flex items-center justify-center animate-bounce">
              <CheckCircle size={40} className="text-green" />
            </div>
            <h3 className="text-[22px] font-bold text-green">Benefit Restored! 🎉</h3>
            <p className="text-[16px] text-text-primary font-medium">
              Your {scheme?.name_en || scheme?.name_hi || 'scheme'} benefit has been successfully restored.
            </p>
            <div className="bg-gradient-to-br from-primary to-[#2563AC] rounded-2xl p-5 text-white">
              <p className="text-[12px] opacity-80">Estimated Annual Recovery</p>
              <p className="text-[28px] font-bold">
                {scheme?.benefit_amount || '₹6,000'}/year
              </p>
            </div>
          </div>
        )

      case 'reminders':
        return (
          <div className="text-center space-y-4">
            <div className="w-16 h-16 mx-auto rounded-full bg-primary-light flex items-center justify-center">
              <Bell size={32} className="text-primary" />
            </div>
            <h3 className="text-[18px] font-bold">Future Reminders Enabled</h3>
            <p className="text-[14px] text-text-secondary">
              Get notified before your scheme is due for renewal or eKYC.
            </p>
            <div className="flex items-center justify-center gap-3 bg-primary-light rounded-2xl p-4">
              <Bell size={20} className="text-primary" />
              <span className="text-[14px] font-medium text-primary">Enable Reminders</span>
              <button
                onClick={() => setRemindersEnabled(!remindersEnabled)}
                className={`relative w-12 h-6 rounded-full transition-colors ${remindersEnabled ? 'bg-green' : 'bg-gray-300'}`}
              >
                <div className={`absolute top-0.5 w-5 h-5 rounded-full bg-white shadow transition-transform ${remindersEnabled ? 'translate-x-6' : 'translate-x-0.5'}`} />
              </button>
            </div>
            <p className="text-[12px] text-text-secondary">
              {remindersEnabled ? 'You will receive notifications for upcoming renewals' : 'Reminders are disabled'}
            </p>
          </div>
        )

      default:
        return null
    }
  }

  return (
    <div className="min-h-screen flex flex-col">
      <div className="flex items-center justify-between px-4 py-3">
        <button onClick={onClose} className="p-2" style={{ minHeight: '44px', minWidth: '44px' }}>
          <X size={22} className="text-primary" />
        </button>
        <h2 className="text-[16px] font-bold truncate flex-1 text-center mx-2">
          {scheme?.name_en || 'Revival Journey'}
        </h2>
        <div style={{ width: 44 }} />
      </div>

      <div className="mx-4 h-1.5 bg-gray-100 rounded-full overflow-hidden mb-2">
        <div className="h-full bg-primary rounded-full transition-all duration-500" style={{ width: `${progress}%` }} />
      </div>

      <div className="overflow-x-auto px-4 pb-2" style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}>
        <div className="flex gap-1 min-w-max">
          {steps.map((s, i) => {
            const isActive = i === currentStep
            const isDone = i < currentStep
            const Icon = s.icon
            return (
              <button key={s.key}
                onClick={() => setCurrentStep(i)}
                className={`flex flex-col items-center gap-1 px-2 py-1.5 rounded-xl transition-all min-w-[56px] ${
                  isActive ? 'bg-primary text-white' : isDone ? 'text-green' : 'text-gray-400'
                }`}>
                <Icon size={16} />
                <span className="text-[8px] font-medium leading-tight text-center">{s.label}</span>
              </button>
            )
          })}
        </div>
      </div>

      <div className="flex-1 px-4 py-4 overflow-y-auto">
        <div className="page-enter" key={currentStep}>
          {renderStep()}
        </div>
      </div>

      <div className="flex gap-3 px-4 py-4 border-t border-gray-100">
        <button
          onClick={handleBack}
          disabled={isFirst}
          className="btn-secondary flex-1 flex items-center justify-center gap-2"
        >
          <ArrowLeft size={18} />
          Back
        </button>
        <button
          onClick={isLast ? onClose : handleNext}
          className="btn-primary flex-1 flex items-center justify-center gap-2"
        >
          {isLast ? 'Finish' : 'Next'}
          <ArrowRight size={18} />
        </button>
      </div>
    </div>
  )
}
