import { useState } from 'react'
import { useApp } from '../store/appStore'
import { ArrowLeft, Download, ExternalLink, MapPin, CheckCircle, ChevronRight, Lightbulb, AlertTriangle, Clock, CheckSquare } from 'lucide-react'

export default function RevivalPage({ schemeId, onBack }) {
  const { t, lang, scanResults, profile, applyScheme, fetchApplications, setPage } = useApp()
  const [tab, setTab] = useState('explain')
  const [formData, setFormData] = useState({})
  const [submitted, setSubmitted] = useState(false)
  const [showSimple, setShowSimple] = useState(false)

  const allItems = [
    ...(scanResults?.results?.lapsed || []),
    ...(scanResults?.results?.at_risk || []),
    ...(scanResults?.results?.eligible_unclaimed || []),
  ]
  const item = allItems.find(x => x.scheme_id === schemeId)

  if (!item) {
    return (
      <div className="p-4">
        <button onClick={onBack} className="btn-secondary mb-4"><ArrowLeft size={18} /> {lang === 'hi' ? 'वापस' : 'Back'}</button>
        <p className="text-center text-text-secondary">{lang === 'hi' ? 'योजना नहीं मिली' : 'Scheme not found'}</p>
      </div>
    )
  }

  // Build simple Hindi explanation based on detected reasons
  const simpleExplanations = item.reasons_hi?.length
    ? item.reasons_hi.map((r, i) => {
        const en = item.reasons_en?.[i] || r
        const hi = r
        return {
          hi: `• ${hi}`,
          en: `• ${en}`
        }
      })
    : [
        { hi: '• आपकी योजना का समय पूरा हो गया है', en: '• Your scheme period has expired' },
        { hi: '• कृपया नए सिरे से आवेदन करें', en: '• Please re-apply' },
      ]

  const simpleExplanationText = lang === 'hi'
    ? `आपकी ${item.name_hi} में निम्नलिखित समस्या पाई गई:\n\n${simpleExplanations.map(e => e.hi).join('\n')}\n\nइसे ठीक करने के लिए दिए गए चरणों का पालन करें।`
    : `The following issues were detected in your ${item.name_en}:\n\n${simpleExplanations.map(e => e.en).join('\n')}\n\nFollow the steps below to fix this.`

  const steps = item.reasons_hi?.length
    ? item.reasons_hi.map((r, i) => ({
        hi: `✅ ${item.reasons_en?.[i] ? item.reasons_en[i] : r}`,
        en: `✅ ${item.reasons_en?.[i] || r}`
      }))
    : [
        { hi: '✅ eKYC अपडेट करने के लिए निकटतम CSC केंद्र पर जाएँ', en: '✅ Visit nearest CSC center for eKYC update' },
        { hi: '✅ आवश्यक दस्तावेज़ जमा करें', en: '✅ Submit required documents' },
        { hi: '✅ ऑनलाइन आवेदन या सीएससी के माध्यम से आवेदन करें', en: '✅ Apply online or through CSC' },
      ]

  // Timeline
  const timelineItems = item.timeline || []

  const handleSubmitForm = async () => {
    try {
      await applyScheme(schemeId, formData)
      setSubmitted(true)
      fetchApplications()
    } catch (err) {
      console.error('Application error:', err)
    }
  }

  const handleDownloadPDF = () => {
    let content = `${item.name_hi}\n${item.name_en}\n\n`
    content += `${lang === 'hi' ? 'आवेदन पत्र' : 'Application Form'}\n\n`
    content += `${lang === 'hi' ? 'प्रोफ़ाइल जानकारी' : 'Profile Information'}:\n`
    content += `${lang === 'hi' ? 'नाम' : 'Name'}: ${profile?.name || ''}\n`
    content += `${lang === 'hi' ? 'आयु' : 'Age'}: ${profile?.age || ''}\n`
    content += `${lang === 'hi' ? 'राज्य' : 'State'}: ${profile?.state || ''}\n`
    content += `${lang === 'hi' ? 'ज़िला' : 'District'}: ${profile?.district || ''}\n`
    content += `${lang === 'hi' ? 'व्यवसाय' : 'Occupation'}: ${profile?.occupation || ''}\n\n`
    content += `${lang === 'hi' ? 'आवश्यक जानकारी' : 'Required Information'}:\n`
    const fields = [
      { hi: 'आधार संख्या', en: 'Aadhaar Number' },
      { hi: 'बैंक खाता संख्या', en: 'Bank Account Number' },
      { hi: 'IFSC कोड', en: 'IFSC Code' },
      { hi: 'मोबाइल नंबर', en: 'Mobile Number' },
    ]
    fields.forEach(f => {
      content += `${lang === 'hi' ? f.hi : f.en}: _______________\n`
    })
    content += `\n---\n${lang === 'hi' ? 'यह फ़ॉर्म Scheme Sarthi द्वारा तैयार किया गया है' : 'This form is generated by Scheme Sarthi'}\n`
    content += `${lang === 'hi' ? 'DPDP अनुपालन: आपका डेटा आपके पास रहता है' : 'DPDP compliant: Your data stays with you'}\n`

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `scheme-sarthi-${schemeId}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  if (submitted) {
    return (
      <div className="p-4 flex flex-col items-center justify-center min-h-[60vh]">
        <div className="w-16 h-16 rounded-full bg-green/10 flex items-center justify-center mb-4">
          <CheckCircle size={32} className="text-green" />
        </div>
        <p className="text-[18px] font-semibold text-center mb-2">
          {lang === 'hi' ? 'आवेदन सफलतापूर्वक जमा कर दिया गया!' : 'Application submitted successfully!'}
        </p>
        <p className="text-[14px] text-text-secondary text-center mb-6">
          {lang === 'hi' ? 'आपका आवेदन प्राप्त हो गया है।' : 'Your application has been received.'}
        </p>
        <button onClick={() => setPage('applications')} className="btn-primary">
          {lang === 'hi' ? 'स्थिति देखें' : 'View Status'}
        </button>
        <button onClick={() => setPage('results')} className="btn-secondary mt-3">
          {lang === 'hi' ? 'डैशबोर्ड पर वापस' : 'Back to Dashboard'}
        </button>
      </div>
    )
  }

  return (
    <div className="pb-8">
      <div className="flex items-center gap-2 px-4 py-3">
        <button onClick={onBack} className="p-2" style={{ minHeight: '44px', minWidth: '44px' }}>
          <ArrowLeft size={22} className="text-primary" />
        </button>
        <h1 className="text-[18px] font-bold truncate flex-1">{lang === 'hi' ? item.name_hi : item.name_en}</h1>
        {item.priority && (
          <span className={`px-2 py-1 rounded text-[11px] font-semibold ${
            item.priority === 'Critical' ? 'bg-danger/10 text-danger' :
            item.priority === 'High' ? 'bg-warning/10 text-warning' :
            'bg-primary-light text-primary'
          }`}>
            {item.priority}
          </span>
        )}
      </div>

      {/* Consequence Preview */}
      {item.consequence_hi && (
        <div className="mx-4 mb-4 bg-danger/5 border border-danger/20 rounded-2xl p-3">
          <div className="flex items-start gap-2">
            <AlertTriangle size={16} className="text-danger flex-shrink-0 mt-0.5" />
            <p className="text-[13px] text-danger/80">
              <span className="font-semibold">{lang === 'hi' ? 'अनदेखा करने पर:' : 'If ignored:'}</span>{' '}
              {lang === 'hi' ? item.consequence_hi : item.consequence_en}
            </p>
          </div>
        </div>
      )}

      {/* Recovery Estimate */}
      {item.recovery && (
        <div className="mx-4 mb-4 flex gap-2">
          <div className="flex-1 bg-green/5 rounded-xl p-2.5 text-center">
            <p className="text-[11px] text-text-secondary">{lang === 'hi' ? 'समय' : 'Time'}</p>
            <p className="text-[15px] font-bold text-green">{item.recovery.estimated_minutes} {lang === 'hi' ? 'मिनट' : 'min'}</p>
          </div>
          <div className="flex-1 bg-primary-light rounded-xl p-2.5 text-center">
            <p className="text-[11px] text-text-secondary">{lang === 'hi' ? 'कठिनाई' : 'Difficulty'}</p>
            <p className="text-[15px] font-bold text-primary">
              {lang === 'hi'
                ? (item.recovery.difficulty_hi === 'Easy' ? 'आसान' : item.recovery.difficulty_hi === 'Medium' ? 'मध्यम' : 'कठिन')
                : item.recovery.difficulty_en}
            </p>
          </div>
          <div className="flex-1 bg-amber-50 rounded-xl p-2.5 text-center">
            <p className="text-[11px] text-text-secondary">{lang === 'hi' ? 'कार्यालय' : 'Office'}</p>
            <p className="text-[15px] font-bold text-warning">{item.recovery.office_visit_required ? (lang === 'hi' ? 'हाँ' : 'Yes') : (lang === 'hi' ? 'नहीं' : 'No')}</p>
          </div>
        </div>
      )}

      {/* What went wrong explainer */}
      <div className="bg-primary-light rounded-2xl mx-4 p-4 mb-4">
        <div className="flex items-start gap-2">
          <div className="w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center flex-shrink-0">
            <Lightbulb size={16} className="text-primary" />
          </div>
          <div>
            <p className="text-[15px] font-semibold text-primary mb-1">{item.benefit_amount}</p>
            <p className="text-[14px] text-text-secondary">
              {lang === 'hi' ? item.reason_hi : item.reason_en}
            </p>
          </div>
        </div>
      </div>

      {/* Explain Simply button */}
      <div className="mx-4 mb-4">
        <button
          onClick={() => setShowSimple(!showSimple)}
          className="btn-secondary text-[13px]"
        >
          <Lightbulb size={16} />
          {lang === 'hi' ? 'सरल भाषा में समझाएँ' : 'Explain Simply'}
        </button>
        {showSimple && (
          <div className="mt-3 bg-white border border-primary/20 rounded-2xl p-4 shadow-card">
            <p className="text-[14px] text-text-primary whitespace-pre-line leading-relaxed">
              {simpleExplanationText}
            </p>
            <div className="mt-3 pt-3 border-t border-gray-100">
              <p className="text-[12px] text-text-secondary">
                {lang === 'hi' ? 'Confidence:' : 'Confidence:'} {item.confidence || 'High'}
                {' | '}
                {lang === 'hi' ? 'नियम-आधारित मिलान' : 'Rule-based matching'}
              </p>
            </div>
          </div>
        )}
      </div>

      {/* Timeline */}
      {timelineItems.length > 0 && (
        <div className="mx-4 mb-4">
          <h3 className="text-[14px] font-semibold mb-2">
            {lang === 'hi' ? 'भुगतान / नवीनीकरण इतिहास' : 'Payment / Renewal History'}
          </h3>
          <div className="bg-white rounded-2xl p-4 shadow-card">
            <div className="flex items-start gap-2">
              <div className="flex flex-col items-center gap-1">
                {timelineItems.map((tl, i) => (
                  <div key={i} className="flex items-center gap-2">
                    <div className={`w-6 h-6 rounded-full flex items-center justify-center text-[11px] ${
                      tl.status === 'paid' ? 'bg-green text-white' :
                      tl.status === 'warning' ? 'bg-warning text-white' :
                      tl.status === 'missed' ? 'bg-danger text-white' :
                      'bg-gray-200 text-gray-500'
                    }`}>
                      {tl.status === 'paid' ? '✓' : tl.status === 'missed' ? '✗' : '○'}
                    </div>
                    <span className={`text-[13px] ${
                      tl.status === 'paid' ? 'text-green font-medium' :
                      tl.status === 'missed' ? 'text-danger' :
                      'text-text-secondary'
                    }`}>
                      {lang === 'hi' ? tl.label_hi : tl.label_en}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Tabs */}
      <div className="flex gap-1 px-4 mb-4">
        {['explain', 'form', 'docs'].map(tabKey => (
          <button
            key={tabKey}
            onClick={() => setTab(tabKey)}
            className={`flex-1 py-2.5 rounded-xl font-medium text-[13px] transition-all ${
              tab === tabKey
                ? 'bg-primary text-white'
                : 'bg-primary-light/50 text-text-secondary'
            }`}
            style={{ minHeight: '40px' }}
          >
            {tabKey === 'explain' ? (lang === 'hi' ? 'सुधारें' : 'Fix') :
             tabKey === 'form' ? (lang === 'hi' ? 'फ़ॉर्म' : 'Form') :
             (lang === 'hi' ? 'दस्तावेज़' : 'Docs')}
          </button>
        ))}
      </div>

      <div className="px-4">
        {tab === 'explain' && (
          <div>
            <div className="bg-amber-50 border border-warning/20 rounded-2xl p-4 mb-4">
              <p className="text-[14px] font-semibold text-warning mb-1">{t('revival.what_wrong')}</p>
              <p className="text-[14px] text-text-secondary">
                {lang === 'hi' ? item.reason_hi : item.reason_en}
              </p>
            </div>

            <h3 className="text-[16px] font-semibold mb-3">{t('revival.steps')}</h3>
            <div className="space-y-3 mb-6">
              {steps.map((step, i) => (
                <div key={i} className="flex items-start gap-3 bg-white rounded-2xl p-4 shadow-card">
                  <div className="w-7 h-7 rounded-full bg-green/10 flex items-center justify-center flex-shrink-0 mt-0.5">
                    <CheckCircle size={16} className="text-green" />
                  </div>
                  <p className="text-[14px] text-text-primary">{lang === 'hi' ? step.hi : step.en}</p>
                </div>
              ))}
            </div>

            <div className="bg-primary-light/50 rounded-2xl p-4 mb-4">
              <p className="text-[14px] font-semibold mb-3">{t('revival.submit_at')}</p>
              {item.apply_url && (
                <a href={item.apply_url} target="_blank" rel="noopener noreferrer"
                  className="flex items-center gap-2 text-primary font-medium mb-3 hover:underline"
                  style={{ minHeight: '44px' }}>
                  <ExternalLink size={16} />
                  {t('revival.apply_online')}
                </a>
              )}
              <div className="flex items-center gap-2 text-text-secondary text-[14px]">
                <MapPin size={16} />
                {t('revival.csc')}
              </div>
            </div>

            {item.matched_rules && item.matched_rules.length > 0 && (
              <div className="bg-white rounded-2xl p-4 shadow-card mb-4">
                <p className="text-[13px] font-semibold mb-2">
                  {lang === 'hi' ? 'मिलान किए गए नियम' : 'Matched Rules'}
                </p>
                {item.matched_rules.map((r, i) => (
                  <div key={i} className="flex items-center gap-2 py-1">
                    <CheckSquare size={14} className="text-green" />
                    <span className="text-[12px] text-text-secondary">
                      {r.field}: {String(r.actual)} {r.operator} {String(r.expected)}
                    </span>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        {tab === 'form' && (
          <div>
            <h3 className="text-[16px] font-semibold mb-4">{t('revival.fill_form')}</h3>
            <div className="space-y-4">
              {[
                { name: 'aadhaar', label_hi: 'आधार संख्या', label_en: 'Aadhaar Number', type: 'text' },
                { name: 'bank_account', label_hi: 'बैंक खाता संख्या', label_en: 'Bank Account Number', type: 'text' },
                { name: 'ifsc', label_hi: 'IFSC कोड', label_en: 'IFSC Code', type: 'text' },
                { name: 'mobile', label_hi: 'मोबाइल नंबर', label_en: 'Mobile Number', type: 'tel' },
              ].map(f => (
                <div key={f.name} className="floating-label">
                  <label className="font-medium text-[13px] mb-1 block text-text-secondary">
                    {lang === 'hi' ? f.label_hi : f.label_en}
                  </label>
                  <input
                    type={f.type}
                    value={formData[f.name] || ''}
                    onChange={e => setFormData(prev => ({ ...prev, [f.name]: e.target.value }))}
                    className="form-input"
                    placeholder={lang === 'hi' ? f.label_hi : f.label_en}
                  />
                </div>
              ))}
            </div>

            {/* Pre-filled from profile */}
            <div className="mt-4 bg-primary-light/50 rounded-2xl p-3">
              <p className="text-[12px] font-medium text-text-secondary mb-1">
                {lang === 'hi' ? 'प्रोफ़ाइल से प्री-फ़िल्ड' : 'Pre-filled from profile'}
              </p>
              <div className="text-[13px] text-text-primary space-y-1">
                <p>{lang === 'hi' ? 'नाम' : 'Name'}: {profile?.name || '-'}</p>
                <p>{lang === 'hi' ? 'आयु' : 'Age'}: {profile?.age || '-'}</p>
                <p>{lang === 'hi' ? 'राज्य' : 'State'}: {profile?.state || '-'}</p>
                <p>{lang === 'hi' ? 'ज़िला' : 'District'}: {profile?.district || '-'}</p>
              </div>
            </div>

            <div className="flex gap-3 mt-6">
              <button onClick={handleSubmitForm} className="btn-primary flex-1">
                {t('revival.submit')}
              </button>
            </div>

            <button onClick={handleDownloadPDF} className="btn-secondary mt-3">
              <Download size={18} />
              {t('revival.download_pdf')}
            </button>
          </div>
        )}

        {tab === 'docs' && (
          <div>
            <h3 className="text-[16px] font-semibold mb-4">{t('revival.documents')}</h3>
            {item.recovery && (
              <p className="text-[13px] text-text-secondary mb-3">
                {lang === 'hi' ? 'आवश्यक दस्तावेज़' : 'Required documents'}: {item.recovery.documents_required}
              </p>
            )}
            <div className="space-y-3">
              {(item.documents || [
                'आधार कार्ड (Aadhaar Card)',
                'बैंक खाता विवरण (Bank Account Details)',
                'पासपोर्ट साइज़ फोटो (Passport Photo)',
                'निवास प्रमाण पत्र (Residence Proof)',
              ]).map((doc, i) => (
                <div key={i} className="flex items-center gap-3 bg-white rounded-2xl p-4 shadow-card">
                  <div className="w-10 h-10 rounded-full bg-primary-light flex items-center justify-center flex-shrink-0">
                    <span className="text-[16px]">📄</span>
                  </div>
                  <p className="text-[14px] text-text-primary">{doc}</p>
                </div>
              ))}
            </div>

            <div className="mt-6 bg-warning/5 border border-warning/20 rounded-2xl p-4">
              <p className="text-[13px] text-text-secondary">
                {lang === 'hi'
                  ? 'ये दस्तावेज़ निकटतम CSC केंद्र या संबंधित विभाग में जमा करें।'
                  : 'Submit these documents at your nearest CSC center or concerned department.'}
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
